export default [
    {
    id: 1,
    firm: 'Microsoft',
    date: "2022-12-04",
    via: "Linkedin",
    job: "Développeur Full stack React - Node",
    comment: "Entretien sympa avec Lead - attente de test technique",
    status: "waiting",
    },
    {
    id: 2,
    firm: 'Degetel - ESN',
    date: "2022-01-12",
    via: "-",
    job: "Développeur Mobile",
    comment: "Appel de leur part - Pas intéressé",
    status: "refused",
    },
    {
    id: 3,
    firm: 'Le Monde - Journal',
    date: "2022-01-14",
    via: "Choose your boss",
    job: "Développeur Front-end",
    comment: "Bon échange en entretien - Test technique ok",
    status: "accepted",
    },
    {
    id: 4,
    firm: 'Capgemini - ESN',
    date: "2022-01-15",
    via: "-",
    job: "Développeur Full Stack JS",
    comment: "Appel de leur part - A voir s'il ont des offres clients",
    status: "waiting",
    },
    {
    id: 5,
    firm: 'Google',
    date: "2022-01-16",
    via: "Apec",
    job: "Développeur Back-end NodeJs",
    comment: "Candidature refusée - pas de motif",
    status: "refused",
    },
];